MujocoPlugins:
  - type: HydroelasticContactSurface
    SurfacePlugins:
      - { type: HydroelasticContactSurfaceSensor/FlatTactileSensor, sensorName: "myrmex_sensor0", geomName: "myrmex_foam", topicName: "/tactile_module_16x16_v2", updateRate: 50.0, visualize: True, use_parallel: True, resolution: 0.025, sampling_resolution: 20 }
